"""Writes inflate_vectors.h: the test pattern from test_dax.cpp's
inflate_pattern() compressed by Python's zlib, once with dynamic Huffman
codes and once with fixed codes (raw DEFLATE, no zlib header).
Run with any Python 3: python make_inflate_vectors.py"""
import os
import zlib

data = bytes(((i * 7) ^ (i >> 4)) & 0xFF for i in range(1200)) + b"the gold box " * 40 + bytes(range(256)) * 3

out = ["// Generated by make_inflate_vectors.py - do not edit.", "#pragma once", "#include <cstdint>", ""]
for name, strategy in (("kDeflateDynamic", zlib.Z_DEFAULT_STRATEGY), ("kDeflateFixed", zlib.Z_FIXED)):
    c = zlib.compressobj(9, zlib.DEFLATED, -15, 9, strategy)
    z = c.compress(data) + c.flush()
    out.append(f"static const uint8_t {name}[{len(z)}] = {{")
    for i in range(0, len(z), 20):
        out.append("    " + ", ".join(f"0x{b:02X}" for b in z[i:i + 20]) + ",")
    out.append("};")
    out.append("")
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "inflate_vectors.h"), "w") as f:
    f.write("\n".join(out))
